# Generated by Django 4.1.7 on 2023-03-30 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Andhra',
            fields=[
                ('stno', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dname', models.CharField(max_length=100)),
                ('areas', models.CharField(max_length=100, unique=True)),
                ('stno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.andhra')),
            ],
        ),
        migrations.CreateModel(
            name='Mandal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.district')),
            ],
        ),
    ]
